### Request OTP
POST http://localhost:5000/auth/request-otp
Content-Type: application/json

{
  "email": "my@example.com"
}

### Verify OTP
POST http://localhost:5000/auth/verify-otp
Content-Type: application/json

{
  "email": "my@example.com",
  "otp": "399397"
}

### Refresh Token
POST http://localhost:5000/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImlhdCI6MTc1NjkwMzMxNCwiZXhwIjoxNzU3NTA4MTE0fQ._Y0-LDKX0DYNrOhE1AInBeH6qSg55fMUMXsgbeRfOiU"
}

### Get All Books
GET http://localhost:5000/books?page=1&limit=5

### Get Book by ID
GET http://localhost:5000/books/15

### Create Book (requires authentication)
POST http://localhost:5000/books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImlhdCI6MTc1NjkwMzMxNCwiZXhwIjoxNzU2OTA0MjE0fQ.dyJ6PoipUM-C0yKu7LiKIqIEBEmekPCDZJeGK9B4VaQ

  {
    "title": "Shining",
    "author": "Stephen King",
    "published_year": 1977,
    "price": 13.99
  }

### Update Book (requires authentication)
PUT http://localhost:5000/books/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImlhdCI6MTc1NjkwMzMxNCwiZXhwIjoxNzU2OTA0MjE0fQ.dyJ6PoipUM-C0yKu7LiKIqIEBEmekPCDZJeGK9B4VaQ

{
    "published_year": 2000
}

### Delete Book (requires authentication)
DELETE http://localhost:5000/books/15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImlhdCI6MTc1NjkwMzMxNCwiZXhwIjoxNzU2OTA0MjE0fQ.dyJ6PoipUM-C0yKu7LiKIqIEBEmekPCDZJeGK9B4VaQ


# ###
# POST http://localhost:5000/reset-db